#FROM python:3.8-slim
FROM jupyter/scipy-notebook:latest

WORKDIR /docker_jupyter

#RUN pip install numpy && \
#    pip install pandas && \
#    pip install jupyter

#RUN pip install scipy

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser","--allow-root"]
