FROM python:3.8-slim

WORKDIR /docker_jupyter

RUN pip install numpy && \
    pip install pandas && \
    pip install scipy && \
    pip install jupyter

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser","--allow-root"]
